[package]
name = "storage-sqlite"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
async-trait.workspace = true
tokio.workspace = true
rusqlite.workspace = true
anyhow.workspace = true
r2d2.workspace = true
r2d2_sqlite.workspace = true

delta-core = { path = "../delta-core", package = "delta-core" }

