[package]
name = "storage-diesel"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
async-trait.workspace = true
thiserror.workspace = true
uuid.workspace = true
chrono.workspace = true
dotenvy.workspace = true

r2d2 = "0.8"
diesel = { version = "2.1", features = ["sqlite", "r2d2", "chrono", "uuid"] }
tempfile = "3.24.0"

delta-core = { path = "../delta-core", package = "delta-core" }

