[package]
name = "delta-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "delta_core"

[features]
diesel = ["dep:diesel"]

[dependencies]
async-trait.workspace = true
thiserror.workspace = true
anyhow.workspace = true
uuid.workspace = true
serde.workspace = true
chrono.workspace = true
diesel = { version = "2.3", optional = true }
argon2 = "0.6"
getrandom = "0.4"

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
