[package]
name = "tui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "tui"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
ratatui.workspace = true
rand.workspace = true
crossterm.workspace = true
image = { version = "0.25", default-features = false, features = ["png"] }
chrono.workspace = true
serde.workspace = true
serde_yml.workspace = true
clap.workspace = true
reqwest.workspace = true
uuid.workspace = true
delta-api = { path = "../delta-api" }
tokio = { version = "1.53.1", features = ["rt", "rt-multi-thread", "macros"] }
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
rust-i18n = "4"
