[package]
name = "tui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "tui"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
ratatui.workspace = true
crossterm.workspace = true
chrono.workspace = true
serde.workspace = true
uuid.workspace = true