[package]
name = "server"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
axum = { version = "0.8", features = ["macros", "tokio", "http1"] }
tower-http = { version = "0.7", features = ["trace"] }
utoipa = { version = "5", features = ["macros", "chrono", "axum_extras"] }
utoipa-swagger-ui = { version = "9", features = ["axum"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yml.workspace = true
clap.workspace = true
uuid.workspace = true
chrono.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
base64.workspace = true

delta-core = { path = "../delta-core" }
storage-diesel = { path = "../storage-diesel" }
