[package]
name = "server"
version.workspace = true
edition.workspace = true

[dependencies]
# Server-specific (local versions)
axum = { version = "0.8", features = ["macros", "tokio", "http1"] }
tower-http = { version = "0.6", features = ["trace"] }
utoipa = { version = "5", features = ["macros", "chrono"] }
utoipa-swagger-ui = "9"
utoipa-axum = "0.2"

# Shared (workspace = true)
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

 delta-core = { path = "../delta-core" }
thiserror.workspace = true
reqwest = "0.12.24"
# storage-sqlite = { path = "../storage-sqlite" }
